const QUOTES = [
  "No pain, no pizza.",
  "You’re one workout away from lying about being athletic.",
  "Kyllä se siitä… ehkä huomenna.",
  "Sweat is just fat crying quietly.",
  "Today’s forecast: 100% chance of excuses.",
  "Meni vähän suunnitelmat pieleen… taas.",
  "Gym? I thought you said gin.",
  "Progress is slow, but so is Wi-Fi in rural Finland.",
  "If it hurts, it’s probably growth… or injury.",
  "Ei tänään, mutta ehkä ensi viikolla.",
  "I run… out of motivation very quickly.",
  "Lihakset kehittyy, mutta kärsivällisyys ei.",
  "Do it for the future you who pretends this was easy.",
  "I lifted today. Emotionally.",
  "Kyllä tästä vielä urheilija tulee (teoriassa).",
  "Abs are stored in the “someday” folder.",
  "I came, I saw, I skipped leg day.",
  "Motivation is temporary. Sisu is also temporary.",
  "If walking counts, I’m basically an athlete.",
  "Ei jaksa, mutta tehdään silti vähän.",
  "Pain today, bragging rights tomorrow.",
  "I didn’t choose the gym life, the guilt did.",
  "Sisu: 10%. Coffee: 90%.",
  "You miss 100% of the workouts you don’t do… unfortunately.",
  "Tänään kevyesti… eli ei ollenkaan.",
  "Beast mode: currently buffering.",
  "Some call it quitting, I call it strategic resting.",
  "Jos ei nyt, niin ehkä ensi vuonna.",
  "Work out now, complain later.",
  "I flex… my schedule and avoid the gym.",
  "Lupasin itselleni, että aloitan huomenna.",
  "No excuses… except all of them.",
  "Kyllä tämä tästä vielä muuttuu (ei muutu).",
  "Fitness is 20% workout, 80% talking about working out.",
  "I trained hard today: I opened the app.",
  "Ei hätää, huomenna uusi yritys.",
  "Stronger every day… emotionally at least.",
  "I thought about exercising. That counts.",
  "Kivut on väliaikaisia, laiskuus on pysyvää.",
  "Running late counts as cardio, right?",
  "I do my own stunts… like skipping workouts.",
  "Sisu level: loading… stuck at 1%.",
  "If you see me running, something is chasing me.",
  "Ei vielä valmis urheilija, mutta hyvin lähellä sohvaa.",
  "Discipline is just fear of regret.",
  "I lifted today: my phone.",
  "Kyllä tää tästä, sanoi jokainen aloittelija.",
  "Gym membership: expensive decoration.",
  "Work hard, nap harder.",
  "Tänään ei jaksa. Huomenna ehkä vähemmän.",
  "Be better than yesterday… unless yesterday was rest day.",
  "Tänään treeni, huomenna valitus.",
  "Jos hiki ei tule, ainakin tekosyyt tulee.",
  "Sali odottaa. Valitettavasti.",
  "Ei huvita, joten juuri siksi mennään.",
  "Kipu on väliaikaista, laiskuus vähän pysyvämpää.",
  "Tänään vain nopea treeni. (vale)",
  "Jos kävelit jääkaapille, se ei ollut cardio.",
  "Aloitetaan maanantaina. Klassikko.",
  "Treeni tehty. Nyt voi taas maata hyvällä omallatunnolla.",
  "Sohva ei rakenna pakaroita.",
  "Jos ei jaksa, tehdään silti vähän.",
  "Puolikas treeni on enemmän kuin nolla treeniä.",
  "Hengästyminen ei ole persoonallisuus.",
  "Kuntosalikortti ei treenaa puolestasi.",
  "Tänään sattuu huomisen takia.",
  "Tämä tuntui hyvältä idealta eilen.",
  "Urheilin kerran vuonna 2017. Hyvät muistot.",
  "Lihakset kasvavat, kärsivällisyys ei.",
  "Venyttely lasketaan melkein urheiluksi.",
  "Treenikassi pakattu. Se on jo alku.",
  "Jos et jaksa kaikkea, tee vähän.",
  "Miksi juosta vapaaehtoisesti?",
  "Treeni alkaa heti kun löydän motivaation.",
  "Sisu aktivoituu vasta kolmannen kahvin jälkeen.",
  "Hikinen mutta edelleen epävarma.",
  "Tavoitteet korkealla, syke vielä korkeammalla.",
  "En ole laiska, säästän energiaa.",
  "Tämä on character development.",
  "Kyykyt eivät ole ihmisoikeusloukkaus.",
  "Huono treeni on silti treeni.",
  "Tänään nostetaan muutakin kuin odotuksia.",
  "Kipu kertoo että olet hengissä.",
  "Sali kutsuu, en vastaa.",
  "Jos valitat koko treenin ajan, sekin on rytmi.",
  "Vatsalihakset piileskelevät edelleen.",
  "Jos treeni olisi helppoa, kaikki tekisivät sitä.",
  "Lepopäivä ei tarkoita kolmea viikkoa.",
  "Tänään mennään fiiliksellä. Huono idea.",
  "Treeni ensin, kebab myöhemmin.",
  "Hitaasti hyvä tulee. Todella hitaasti.",
  "Minä vastaan ongelmiin kyykyillä.",
  "Jos et kaadu portaissa treenin jälkeen, teitkö edes jalkapäivää?",
  "Tänäänkin voisi olla tekemättä… mutta ei.",
  "Treeni on väliaikaista, screenshot pysyy ikuisesti.",
  "Tänään sattuu, huomenna ehkä enemmän.",
  "Yksi treeni ei tee sankaria, mutta auttaa alkuun.",
  "Salille lähteminen on treenin vaikein osa.",
  "Jos mietit pitäisikö treenata: kyllä.",
  "Ei täydellinen. Vain paikalla.",
  "Treenaa nyt, kiitä itseäsi myöhemmin."
];
